import React from 'react';
import './App.css';

function Privacy() {
  return (
    <div className="container" style={{ alignItems: 'flex-start', textAlign: 'left' }}>
      <div className="main-content" style={{ maxWidth: '800px', margin: '0 auto', padding: '4rem 2rem' }}>
        
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem', color: '#fff' }}>Privacy Policy</h1>
        <p style={{ color: '#888', marginBottom: '3rem' }}>Last Updated: January 5, 2026</p>
        
        <div style={{ color: '#d1d1d1', lineHeight: '1.8' }}>
          
          <h3>1. Introduction</h3>
          <p>
            Welcome to Aervo ("we," "our," or "us"). We are committed to protecting your privacy and ensuring you have 
            a positive experience on our mobile application (the "App") and website. This policy outlines our practices 
            regarding the collection, use, and disclosure of your information.
          </p>

          <h3>2. Information We Collect</h3>
          <p>We collect the following types of information to provide and improve our services:</p>
          <ul style={{ marginLeft: '1.5rem', marginBottom: '1.5rem' }}>
            <li><strong>Account Information:</strong> When you register, we collect your name, email address, and password to secure your account.</li>
            <li><strong>Travel Inputs & Drafts:</strong> We store the itinerary details you manually input (such as locations, dates, and times), as well as <strong>itineraries generated by our AI tools</strong>. This includes <strong>Draft Trips</strong> (incomplete or "Sandbox" itineraries), which are saved to our secure cloud servers to allow you to resume planning across devices.</li>
            <li><strong>Photos and Media:</strong> With your permission, we may access your photo library or camera. This allows you to upload trip cover photos, memories, and travel documents such as <strong>receipts, confirmation numbers, and boarding passes</strong>. We acknowledge that these documents may contain personally identifiable information (PII) such as your legal name, ticket numbers, or payment details. This information is processed for the purposes of <strong>extracting itinerary details via our "Smart Scan" feature and/or providing digital storage for your travel records</strong>, and is stored securely associated with your account.</li>
            <li><strong>Notifications:</strong> We may send you push notifications to remind you of upcoming itinerary events or flight times. You can enable or disable these permissions in your device settings.</li>
            <li><strong>Usage Metrics:</strong> We track interactions with public content, such as how many times a trip is viewed or cloned, to display popularity metrics to the community.</li>
          </ul>

          <h3>3. Location Information</h3>
          <p>
            To provide features like "Nearby Gems," travel suggestions, and itinerary mapping, we may request access to your 
            device's geolocation. You can enable or disable this access at any time through your device settings. 
          </p>

          <h3>4. Community and Collaboration</h3>
          <p>
            <strong>Public Trips:</strong> If you choose to mark a trip as "Public," the itinerary details will be visible to other users on the platform. By making a trip public, you acknowledge and agree that:
          </p>
          <ul style={{ marginLeft: '1.5rem', marginBottom: '10px' }}>
             <li>Exact calendar dates are hidden and replaced with generic days (e.g., "Day 1", "Day 2") to protect your security.</li>
             <li>Other users may <strong>View</strong> and <strong>Clone</strong> (copy) your itinerary into their own account.</li>
             <li>Aggregated statistics (e.g., "1.2k Views", "50 Clones") will be publicly displayed on your trip card.</li>
             <li>You have the option to toggle the visibility of your Author Name and Budget details.</li>
          </ul>
          <p>
            <strong>Group Collaboration:</strong> When you invite specific users to join a private trip, you grant them full access 
            to view and edit that itinerary. We are not responsible for how your invited collaborators use or share this information.
          </p>

          <h3>5. How We Use Artificial Intelligence (AI)</h3>
          <p>
            Aervo uses artificial intelligence technologies to generate travel recommendations. 
            Data you input into the AI planner (such as destination and dates) is processed to provide these services.
          </p>
          <p>
            Additionally, we use AI to <strong>process images you upload</strong> (such as screenshots of tickets or reservations) to automatically extract and autofill itinerary details ("Smart Scan").
            We do not use your personal identifiable information (PII) to train public AI models.
          </p>

          <h3>6. Data Security</h3>
          <p>
            We implement industry-standard security measures (via Google Firebase) to protect your personal information 
            from unauthorized access, alteration, or destruction. However, no method of transmission over the Internet is 100% secure.
          </p>

          <h3>7. Deletion of Data</h3>
          <p>
            You have the right to request the deletion of your account and all associated data. 
            You can perform this action directly within the App's settings menu or by contacting us.
          </p>

          <h3>8. Contact Us</h3>
          <p>
            If you have any questions about this Privacy Policy, please contact us at: <br/>
            <strong style={{ color: '#fff' }}>support@aervo.co</strong>
          </p>
          
          <br />
          <br />
          <a href="/" style={{ color: '#6366f1', textDecoration: 'none', fontWeight: 'bold' }}>&larr; Back to Aervo Home</a>
        </div>

      </div>
      
      <footer className="footer" style={{ width: '100%', textAlign: 'center', borderTop: '1px solid #222' }}>
        <p>© 2026 Aervo LLC. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default Privacy;